###
POST http://localhost:5000/auth/signup 
Content-Type: application/json 

{
    "name": "ammar",
    "phone": "12345678",
    "password": "123",
    "confirmPassword": "123"
}

### login
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "phone": "12345678",
    "password": "123"
}


### register car
POST http://localhost:5000/user/registerCar
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYW1tYXIiLCJ1c2VySWQiOiI2MWFkMTdiM2FlMmFiOWY1MGEwODBjMzQiLCJpYXQiOjE2Mzg3MzQyNjcsImV4cCI6MTYzODczNzg2N30.tBbsvQz0VGvOXvQXHmhIwRyD1P1F6VgSPgUOkKSL_70

{
    "carNumberPlate": "4312",
    "carMake": "Honda",
    "carModel": "Civic",
    "carColor": "White",
    "prodYear": "2009"
}

### register spot

POST http://localhost:5000/user/registerSpot
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYW1tYXIiLCJ1c2VySWQiOiI2MWFkMTdiM2FlMmFiOWY1MGEwODBjMzQiLCJpYXQiOjE2Mzg3MzQyNjcsImV4cCI6MTYzODczNzg2N30.tBbsvQz0VGvOXvQXHmhIwRyD1P1F6VgSPgUOkKSL_70

{
    "spotName": "Abdullah's spot",
    "spotDescription": "Near 5 Star chowrangi",
    "spotLocation": [69.8607, 17.0011],
    "pricePerHour": 250
}

### delete spot

POST http://localhost:5000/user/deleteSpot
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYW1tYXIiLCJ1c2VySWQiOiI2MWE2NTRkMzY0YzMzMWUyMjZhMjAyMjEiLCJpYXQiOjE2MzgyOTQ4NTAsImV4cCI6MTYzODI5ODQ1MH0.VWoN0V3lHgbnaiWF0LaWD2EkWEXhXURr8UgBSJSZH7Y

{
    "spotId": "61a667b8e01f51ccaead6094"
}

###

GET http://localhost:5000/user/getAllUsers

