###
POST http://localhost:5000/auth/signup 
Content-Type: application/json 

{
    "name": "PARKER",
    "phone": "4p",
    "password": "123",
    "confirmPassword": "123"
}

### login
# @name login 
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "phone": "1p",
    "password": "123"
}
###
@generalToken = {{login.response.body.token}}

### switch role
PUT http://localhost:5000/user/switchRole
Content-Type: application/json
Authorization: bearer {{generalToken}}

### add car
POST http://localhost:5000/car/addCar
Content-Type: application/json
Authorization: bearer {{generalToken}}

{
    "model": 
    {
        "numberPlate": "222",
        "make": "BMW",
        "model": "asd",
        "color": "Black",
        "prodYear": "2017"
    }
}

### get all cars
GET http://localhost:5000/car/getAllCarsByParker
Content-Type: application/json
Authorization: bearer {{generalToken}}

### delete car
DELETE http://localhost:5000/car/deleteCar/61dd4a6dc27b32ced1f33cd4
Content-Type: application/json
Authorization: bearer {{generalToken}}


### add spot 1
POST http://localhost:5000/spot
Content-Type: application/json
Authorization: bearer {{generalToken}}

{
    "spotName": "Millenium Mall, Rashid Minhas Road",
    "addressLine1" : "on Rashid minhas road, near Mcdonalds and Shell Petrol Pump",
    "nearestLandmark": "Next to Saima Mall",
    "location": [ 67.115461, 24.900942],
    "pricePerHour": 50
}

### add spot 2
POST http://localhost:5000/spot
Content-Type: application/json
Authorization: bearer {{generalToken}}

{
    "spotName": "Main Safoora Chowrangi",
    "addressLine1" : "Next to Malik Dairy and rangers Chowk.",
    "nearestLandmark": "-",
    "location": [ 67.156612, 24.939279],
    "pricePerHour": 50
}

### add spot 3
POST http://localhost:5000/spot
Content-Type: application/json
Authorization: bearer {{generalToken}}

{
    "spotName": "Main NIPA Chowrangi Center",
    "addressLine1" : "Next to Sadqain marriage lawn.",
    "nearestLandmark": "-",
    "location": [ 67.097099, 24.917846],
    "pricePerHour": 60
}

###########################################
###########################################

### Edit spot
PUT http://localhost:5000/spot/622903f63d9a243f7623c9d3
Content-Type: application/json
Authorization: bearer {{generalToken}}

{
    "name": "Near NIPA Chowrangi Center",
    "addressLine1" : "Very near the Sadqain marriage lawn cut.",
    "nearestLandmark": "-",
    "location": [ 67.097099, 24.917846],
    "pricePerHour": 60
}

### delete spot
DELETE http://localhost:5000/spot/6221b5d2b4de40b5bfc642ca
Content-Type: application/json
Authorization: bearer {{generalToken}}

### get all spots
GET http://localhost:5000/spot/getAllSpots
Content-Type: application/json
Authorization: bearer {{generalToken}}

### get all spots by seller
GET http://localhost:5000/spot/getSpotsBySeller?filter=1
Content-Type: application/json
Authorization: bearer {{generalToken}}

### get spots by radius
GET http://localhost:5000/spot/getSpotsByRadius?lat=24.942960&lng=67.158914&radius=5
Content-Type: application/json
Authorization: bearer {{generalToken}}

###
GET http://localhost:5000/user/getUserByRole/61da3982198da5dd6c0bc9f0
Authorization: bearer {{generalToken}}

###
GET http://localhost:5000/bookingRequest/sellerRequests?filter=pending
Authorization: bearer {{generalToken}}

###
GET http://localhost:5000/bookingRequest/parkerRequests?filter=all
Authorization: bearer {{generalToken}}














###########################################
###########################################
################# DEV  ####################
################# APIs ####################
###########################################
###########################################

GET http://localhost:5000/user/getUser/61da3991198da5dd6c0bc9f9
Authorization: bearer {{generalToken}}
