
###
POST http://localhost:5000/auth/signup 
Content-Type: application/json 

{
    "name": "Ammar Parker",
    "phone": "1p",
    "password": "123",
    "confirmPassword": "123"
}

### login
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "phone": "1p",
    "password": "123"
}

### switch role
PUT http://localhost:5000/user/switchRole
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQW1tYXIgUGFya2VyIiwidXNlcklkIjoiNjFkYTM5OTExOThkYTVkZDZjMGJjOWY5IiwiaWF0IjoxNjQxODgzMTk3LCJleHAiOjE2NDE4ODY3OTd9.0hsLAiYO5iCzCGNV8pWOCV4kLDE6cOc_QcJSd2nRYdw


### add car
POST http://localhost:5000/car/addCar
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQW1tYXIgUGFya2VyIiwidXNlcklkIjoiNjFkYTM5OTExOThkYTVkZDZjMGJjOWY5IiwiaWF0IjoxNjQxODgzMTk3LCJleHAiOjE2NDE4ODY3OTd9.0hsLAiYO5iCzCGNV8pWOCV4kLDE6cOc_QcJSd2nRYdw

{
    "numberPlate": "9999",
    "make": "Corolla",
    "model": "Toyota",
    "color": "Blue",
    "prodYear": "2007"
}

### delete car
DELETE http://localhost:5000/car/deleteCar
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQW1tYXIgUGFya2VyIiwidXNlcklkIjoiNjFkYTM5OTExOThkYTVkZDZjMGJjOWY5IiwiaWF0IjoxNjQxODgzMTk3LCJleHAiOjE2NDE4ODY3OTd9.0hsLAiYO5iCzCGNV8pWOCV4kLDE6cOc_QcJSd2nRYdw

{
    "carId" : "61dd2721f8399c8302da4683"
}

### register spot

POST http://localhost:5000/spot/registerSpot
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWJkdWxsYWggU2VsbGVyIiwidXNlcklkIjoiNjFkYTM5ODIxOThkYTVkZDZjMGJjOWYyIiwiaWF0IjoxNjQxNzMyOTg3LCJleHAiOjE2NDE3MzY1ODd9.gk_DqPqXDw5bq1UzpZp0djb0wuJZ36sHaWJ451AzQrw

{
    "name": "Abdullah's spot",
    "addressLine1" : "Safoora, Sector 1, Scheme 33",
    "nearestLandmark": "Near X Flats",
    "location": [67.04038400013158, 25.01522262464436],
    "pricePerHour": 10
}

### delete spot

POST http://localhost:5000/spot/deleteSpot
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYW1tYXIiLCJ1c2VySWQiOiI2MWFlNTY0Y2VlOWJmZDE4YjMwNTNiMzkiLCJpYXQiOjE2Mzg4MTU4ODUsImV4cCI6MTYzODgxOTQ4NX0.BYCz61WdWOVA6m_l2oDq4-qeKnoxgGw6y_Sf6Nc4cZ4

{
    "spotId": "61a667b8e01f51ccaead6094"
}

###

GET http://localhost:5000/user/getAllUsers


###

GET http://localhost:5000/user/getUser/61da3991198da5dd6c0bc9f9
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQW1tYXIgUGFya2VyIiwidXNlcklkIjoiNjFkYTM5OTExOThkYTVkZDZjMGJjOWY5IiwiaWF0IjoxNjQxODg3NjMzLCJleHAiOjE2NDE4OTEyMzN9.oD9QKCZ05HOMpWBvzKQ0057YEPZE7M__q9DnqeMJMhI

