### login
# @name login
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "phone": "1s",
    "password": "123"
}
###
@generalToken = {{login.response.body.token}}


### get all notifications
DELETE http://localhost:5000/bookingRequest/629ceaece84e67d7b6841be9
Content-Type: application/json
Authorization: Bearer {{generalToken}}

